[package]
name = "dynstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inventory = { version = "0.2.*", optional = true }
once_cell = "*"

[features]
inventory = ["dep:inventory"]
